#!/bin/bash

echo -e "================================================="
echo -e ""  
echo -e "» menu         : Menampilkan daftar perintah"
echo -e "» usernew      : Membuat akun SSH & OpenVPN"
echo -e "» trial        : Membuat akun trial"
echo -e "» hapus        : Menghapus akun SSH & OpenVPN"
echo -e "» cek          : Cek user login"
echo -e "» member       : Daftar member SSH & OpenVPN"
echo -e "» delexp       : Delete user expired"
echo -e "» resvis       : Restart service Dropbear, Webmin"
echo -e "                 Squid3, OpenVPN, SSH dan SSL"
echo -e "» reboot       : Reboot VPS"
echo -e "» speedtest    : Speedtest VPS"
echo -e "» info         : Menampilkan informasi sistem"
echo -e "» exit         : Keluar dari terminal SSH"
echo -e ""
echo -e "================================================="
